### ISSUE TITLE
Excel module does not work in production mode

### ISSUE THREAD

**Issue by pepite** [greenlaw110/play-excel#1]
I have the following error when running on production mode, with the sample application. This is because Play! tries to pre compile the template, which is not a good idea of course. 

Please note that it might really well be a problem in play! but I prefer to log the problem here as well.

00:26:04,298 INFO  ~ Module excel is available (/Users/nicolas/Projects/Personal/play-excel/sample/excel/../..)
00:26:04,461 INFO  ~ Precompiling ...
00:26:09,992 ERROR ~ Template /app/views/Application/generateNameCard.xls does not compile at line 2
00:26:09,995 ERROR ~ 

@623a639gd
Cannot start in PROD mode with errors

Template compilation error (In /app/views/Application/generateNameCard.xls around line 2)
The template /app/views/Application/generateNameCard.xls does not compile : expecting anything but ''\n''; got it anyway 

play.exceptions.TemplateCompilationException: expecting anything but ''\n''; got it anyway 
    at play.templates.Template.compile(Template.java:203)
    at play.templates.TemplateLoader.scan(TemplateLoader.java:138)

**Comment by greenlaw110** [comment]
Fixed in v1.2
